language: node_js
node_js:
  - "6"
  - "5"
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm test
install:
  - npm install --dev
before_install:
  - "npm update -g npm"
after_success:
  - bash <(curl -s https://codecov.io/bash)
